<a href="https://colab.research.google.com/github/alwayspulakraj/GENERATIVE_AI_COURSE_ASSIGNMENT/blob/ASSIGNMENTS-PW-SKILLS/Data_Toolkit_assignment/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr=np.arange(6)
print(arr)
print(type(arr))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#2. Given a NumPy array 'arr', check if its data type is float64, arr = np.array([1.5, 2.6, 3.7])
arr = np.array([1.5, 2.6, 3.7])
arr.dtype#we can also print the the type to show only the data type

dtype('float64')

In [ ]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([1+2j,3+4j,5+6j])#complex number
print([arr,arr.dtype])


[array([1.+2.j, 3.+4.j, 5.+6.j]), dtype('complex128')]


In [ ]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr1=np.arange(6)
print("before converting-",arr1.dtype)
arr1=arr1.astype(float)
print("after converting-",arr1.dtype)

before converting- int64
after converting- float64


In [ ]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
print([arr1,arr1.dtype])
arr1=arr1.astype(np.float32)
print([arr1,arr1.dtype])#converted to float32 to reduce decimal precision

[array([0., 1., 2., 3., 4., 5.]), dtype('float64')]
[array([0., 1., 2., 3., 4., 5.], dtype=float32), dtype('float32')]


In [ ]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    print("shape:",arr.shape)
    print("size:",arr.size)
    print("data type:",arr.dtype)

In [ ]:
#7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimmension(arr):
  print("The dimensionality of the inputted array is-",arr.ndim)
arr=np.array([[1,2,3,4]])#This is a example to show the output
array_dimmension(arr)

The dimensionality of the inputted array is- 2


In [ ]:
#8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
  print("item size:",arr.itemsize)
  print("total size in bytes:",arr.nbytes)
ar=np.array(range(5))
print(ar)
item_size_info(ar)

[0 1 2 3 4]
item size: 8
total size in bytes: 40


In [ ]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
  print("strides:",arr.strides)
array_strides(ar)

strides: (8,)


In [ ]:
#10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
  print("shape of the array is -",arr.shape)
  print("strides of the array is -",arr.strides)
shape_stride_relationship(ar)

shape of the array is - (5,)
strides of the array is - (8,)


In [ ]:
#11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
  arr=np.zeros(n)
  print(arr)
n=int(input("Enter number of elements in the array of zeros-"))
create_zeros_array(n)

Enter number of elements in the array of zeros-4
[0. 0. 0. 0.]


In [ ]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_zeros_array(rows,cols):
  arr=np.ones((rows,cols))
  print(arr)
rows=int(input("Enter number of rows-"))
cols=int(input("Enter number of columns-"))
create_zeros_array(rows,cols)

Enter number of rows-3
Enter number of columns-4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified  `step`.
def generate_range_array(start,stop,step):
  arr=np.arange(start,stop,step)
  print(arr)
start=int(input("Enter start-"))
stop=int(input("Enter stop-"))
step=int(input("Enter step-"))
generate_range_array(start,stop,step)

Enter start-1
Enter stop-7
Enter step-2
[1 3 5]


In [ ]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start,stop,num):
  arr=np.linspace(start,stop,num)
  print(arr)
start=float(input("Enter start-"))
stop=float(input("Enter stop-"))
num=int(input("Enter num-"))
generate_linear_space(start,stop,num)

Enter start-0
Enter stop-1
Enter num-10
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
  arr=np.eye(n)
  print(arr)
n=int(input("Enter number-"))
create_identity_matrix(n)

Enter number-3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#16.Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(list):
  a=np.array(list)
  return a
l=[1,2,3,4,5]
list_to_array(l)

array([1, 2, 3, 4, 5])

In [ ]:
#17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr=np.array([1,2,3,4,5])
arr1=arr.view
print(arr1)#<built-in method view of numpy.ndarray object at 0x78428a9f0f90>
#new object created by using the view method of numpy

<built-in method view of numpy.ndarray object at 0x797957fe8db0>


In [ ]:
#18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def func(arr1,arr2):
  arr=np.concatenate((arr1,arr2),axis=1)#by default axis=0
  return arr
arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])
func(arr1,arr2)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
#19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate`.
arr1=np.ones((3,4))
arr2=np.zeros((3,3))#in 2D array axis=0 means vertical and axis =1 means horizontal
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]]


In [ ]:
#20.Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(list):
  arr=np.vstack(list)
  return arr
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=np.array([[7,8,9]])
list=[a,b,c]
vertical_stack(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create(start,stop,step):
  stop+=1
  arr=np.arange(start,stop,step)
  return arr
start=int(input("Enter start-"))
stop=int(input("Enter stop-"))
step=int(input("Enter step-"))
create(start,stop,step)

Enter start-0
Enter stop-10
Enter step-2


array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate(start,stop):
  arr=np.linspace(start,stop,10)
  return arr
start=float(input("Enter start-"))
stop=float(input("Enter stop-"))
generate(start,stop)

Enter start-0
Enter stop-0.01


array([0.        , 0.00111111, 0.00222222, 0.00333333, 0.00444444,
       0.00555556, 0.00666667, 0.00777778, 0.00888889, 0.01      ])

In [ ]:
#23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def log_space():
  arr=np.logspace(1,1000,5)
  return arr
log_space()

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [ ]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
import numpy as np
arr=np.random.randint(1,100,(5,3))
df=pd.DataFrame(arr)
df

0   1   2
0  79  52  50
1  89  27  50
2  58   6  27
3  94  66  52
4  69  51  19

In [ ]:
#25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace(x):
  if x<0:
    return 0
  else:
    return x
arr=np.arange(-10,10)
df=pd.DataFrame(arr)
df.applymap(replace)

0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  1
12  2
13  3
14  4
15  5
16  6
17  7
18  8
19  9

In [ ]:
 #26.Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])
 arr = np.array([10, 20, 30, 40, 50])
 arr[2]

30

In [ ]:
#27.Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

In [ ]:
#28.Using boolean indexing, extract elements greater than 5 from the given NumPy array. arr = np.array([3, 8, 2, 10, 5, 7])
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

In [ ]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [ ]:
#30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr, indexes):
    return arr[indexes[:,0], indexes[:,1]]#the index[:,0] takes the first value of the first element from the set of list in the array and likewise indexes[:,1] takes second element to find the overall index of the array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indexes = np.array([[0, 1], [1, 2], [2, 0]])
result = extract_elements(arr, indexes)
print(result)

[2 6 7]


In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_elements(arr, threshold):
    return arr[arr > threshold]
arr=np.array([1,2,3,4,5,6,7,8,9])
threshold=int(input("Enter threshold-"))
filter_elements(arr,threshold)

Enter threshold-4


array([5, 6, 7, 8, 9])

In [ ]:
#33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
def extract_elements(arr_3d, indexes):
    return arr_3d[indexes[:,0], indexes[:,1], indexes[:,2]]
indexes = np.array([[0, 0, 0], [0, 1, 1], [0, 2, 2]])
print(extract_elements(arr_3d, indexes))  # Output: [1 5 9]

[1 5 9]


In [ ]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np
def filter(arr,con1,con2):
  return arr[(con1)&(con2)]
arr=np.array([1,2,3,4,5,6,7,8,9])
con1=arr>5
con2=arr%2==0
filter(arr,con1,con2)

array([6, 8])

In [ ]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def func(arr,indexes):
  return arr[indexes[:,0],indexes[:,1]]
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
indexes=np.array([[0,1],[1,2],[2,2]])
func(arr,indexes)

array([2, 6, 9])

In [ ]:
#36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr=np.random.randn(3,3)
arr+5


array([[4.54951968, 4.2806838 , 4.12720047],
       [5.62611595, 4.5001749 , 4.95267654],
       [5.03782605, 4.6708717 , 5.40125672]])

In [ ]:
#37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr=np.random.randint(1,10,(1,3))
arr1=np.random.randint(1,10,(3,4))
arr2=arr*arr#we can also use np.multiply
arr2

array([[36, 16, 36]])

In [ ]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1=np.random.randint(1,10,(1,4))
arr2=np.random.randint(1,10,(4,3))
result = arr2 + arr1[:, :3]
print(result)

[[17 12 16]
 [16 12 11]
 [15 12 14]
 [18 12 11]]


In [ ]:
#39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1=np.random.randint(1,10,(3,1))
arr2=np.random.randint(1,10,(1,3))
arr1+arr2

array([[17,  9, 10],
       [16,  8,  9],
       [18, 10, 11]])

In [ ]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,2))
np.multiply(arr1,arr2[:,:,np.newaxis])#the values which are left are transfered in this new axis

array([[[18, 48, 18],
        [72, 72, 64]],

       [[ 9, 24,  9],
        [18, 18, 16]]])

In [ ]:
#41.Calculate column wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr,axis=0)#for 2-d array axis=0 for column

array([2.5, 3.5, 4.5])

In [ ]:
#42.Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)#for 2-d array axis=1 for row

array([3, 6])

In [ ]:
#43.For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax()

array([1, 1, 1])

In [ ]:
#44. For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr):
    return np.cumsum()
arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum(arr)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [ ]:
#45.In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr[arr%2==0]

array([2, 4, 6])

In [ ]:
#46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.original_array = np.array([1, 2, 3, 4, 5, 6])
original_array = np.array([1, 2, 3, 4, 5, 6])
m=int(input("Enter m-"))
n=int(input("Enter n-"))
original_array.reshape(m,n)

Enter m-2
Enter n-3


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#47.Create a function that takes a matrix as input and returns the flattened array.
def function(mat):
  a=mat.flatten()
  print(a)
arr=np.random.random_sample((3,3))
mat=np.matrix(arr)
function(mat)

[[0.27655775 0.04313985 0.06558285 0.94301485 0.81403672 0.84143284
  0.88038373 0.63531509 0.34895265]]


In [ ]:
#48.Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1, 2], [3, 4]]),array2 = np.array([[5, 6], [7, 8]])
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
def func(array1,array2):
  return np.concatenate((array1,array2),axis=0)
func(array1,array2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#49.Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def func(original_array):
  return np.split(original_array,3)#splits into 3 sub arrays
func(original_array)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
np.insert(original_array,indices_to_insert,values_to_insert)

array([ 1,  2, 10,  3,  4, 11,  5])

In [ ]:
np.delete(original_array,indices_to_delete)

array([1, 3, 5])

In [ ]:
#51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.Perform element-wise addition between `arr1` and `arr2`.
arr1=np.random.randint(1,100,size=None)
arr2=np.arange(1,11)
arr1+arr2

array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36])

In [ ]:
#52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
arr1-arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [ ]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between `arr1` and `arr2`.
import numpy as np
arr1=np.random.randint(1,100,size=None)
arr2=np.arange(1,6)
arr1*arr2

array([ 8, 16, 24, 32, 40])

In [ ]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
arr1/arr2

array([2., 2., 2., 2., 2.])

In [ ]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.arange(1,6)
arr2=np.arange(5,-0,-1)
arr1**arr2

array([ 1, 16, 27, 16,  5])

In [ ]:
#56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count(arr,substring):
  count=0
  for i in arr:
    if substring in i:
      count+=1
  return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring="hello"
count(arr,substring)

3

In [ ]:
#57.Write a function that extracts uppercase characters from a NumPy array of strings.arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def func(arr):
  for i in arr:
    for j in i:
      if j.isupper():
        print(j,end=" ")
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
func(arr)

H W O A I G P T 

In [ ]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, old_substr, new_substr):
    return np.char.replace(arr, old_substr, new_substr)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substr = 'apple'
new_substr = 'orange'
result = replace_substring(arr, old_substr, new_substr)
print(result)

['orange' 'banana' 'grape' 'pineorange']


In [ ]:
#59. Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World']),arr2 = np.array(['Open', 'AI'])
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def func(arr1,arr2):
  return np.char.add(arr1,arr2)
func(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [ ]:
#60. Write a function that finds the length of the longest string in a NumPy array.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def func(arr):
  max=""
  for i in arr:
    if len(i)>len(max):
      max=i
  return max
func(arr)

'pineapple'

In [ ]:
#61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
arr=np.random.randint(1,1000,size=100)
print("mean=",np.mean(arr))
print("median=",np.median(arr))
print("variance=",np.var(arr))
print("variance=",np.std(arr))

mean= 484.62
median= 457.0
variance= 89851.85559999998
variance= 299.75299097757136


In [ ]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr=np.random.randint(1,100,size=50)
print("25th percentile=",np.percentile(arr,25))
print("75th percentile=",np.percentile(arr,75))

25th percentile= 33.5
75th percentile= 80.5


In [ ]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
arr1=np.random.randint(1,100,size=100)
arr2=np.random.randint(1,100,size=100)
np.corrcoef(arr1,arr2)

array([[1.        , 0.17355972],
       [0.17355972, 1.        ]])

In [ ]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1=np.random.randint(1,100,size=(1,3))
arr2=np.random.randint(1,100,size=(3,3))
mat1=np.matrix(arr1)
mat2=np.matrix(arr2)
np.dot(mat1,mat2)

matrix([[6324, 8273, 3191]])

In [ ]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr=np.random.randint(10,1000,size=50)
print("10th percentile=",np.percentile(arr,10))
print("50th percentile=",np.percentile(arr,50))

10th percentile= 88.9
50th percentile= 619.5


In [ ]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr=np.arange(1,11)
arr[3]

4

In [ ]:
#67. Generate a random NumPy array and sort it in ascending order.
arr=np.random.randint(1,100,size=10)
arr.sort()
arr

array([22, 32, 38, 39, 55, 69, 70, 80, 80, 89])

In [ ]:
#68.Filter elements >20  in the given NumPy array.arr = np.array([12, 25, 6, 42, 8, 30])
arr = np.array([12, 25, 6, 42, 8, 30])
list(filter(lambda x:x if x>20 else None,arr))

[25, 42, 30]

In [ ]:
#69. Filter elements which are divisible by 3 from a given NumPy array.arr = np.array([1, 5, 8, 12, 15])
arr = np.array([1, 5, 8, 12, 15])
list(filter(lambda x:x if x%3==0 else None,arr))

[12, 15]

In [ ]:
#70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.arr = np.array([10, 20, 30, 40, 50])
arr = np.array([10, 20, 30, 40, 50])
list(filter(lambda x:x if x>=20 and x<=40 else None , arr))

[20, 30, 40]

In [ ]:
#71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.arr = np.array([1, 2, 3])
arr = np.array([1, 2, 3])
arr.dtype.byteorder# = means native byte order

'='

In [ ]:
#72.For the given NumPy array, perform byte swapping in place using `byteswap()`.arr = np.array([1, 2, 3], dtype=np.int32)
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [ ]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [ ]:
#74.For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)
native_order = '='
if arr.dtype.byteorder != native_byte_order:
    arr = arr.newbyteorder()
arr.dtype.byteorder

'='

In [ ]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
native_byte_order = '='
if arr.dtype.byteorder != native_byte_order:
    print("Byte swapping is required.")
else:
    print("Byte swapping is not required.")

Byte swapping is not required.


In [ ]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
import numpy as np
arr=np.arange(1,11)
copy_arr=arr.view()#shallow copy
arr[0]=100
print(arr)
print(copy_arr)

[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]


In [ ]:
#77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
arr=np.random.randint(1,10,(3,3))
view_slice=arr[0:2,0:2]
view_slice[0,0]=100
print(arr)
print(view_slice)

[[100   1   8]
 [  1   9   5]
 [  1   6   2]]
[[100   1]
 [  1   9]]


In [ ]:
#78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a=np.arange(1,13).reshape(4,3)
view_b=array_a[0:2,0:2]
view_b+=5
print(array_a)
print(view_b)

[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
[[ 6  7]
 [ 9 10]]


In [ ]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array=np.arange(1,9).reshape(2,4)
reshaped_view=orig_array.reshape(4,2)
reshaped_view[0,0]=100
print(orig_array)#it changes

[[100   2   3   4]
 [  5   6   7   8]]


In [ ]:
#80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
arr=np.random.randint(1,20,(3,4))
import copy
data_copy=arr[arr>5].copy()#deep copy
data_copy[0]=100
print(arr)
print(data_copy)

[[ 9 15  7  7]
 [ 9  4 18 14]
 [ 2 16 15  8]]
[100  15   7   7   9  18  14  16  15   8]


In [ ]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
arr1=np.random.randint(1,10,(3,3))
a=np.matrix(arr1)
arr2=np.random.randint(1,10,(3,3))
b=np.matrix(arr2)
print("addition is-\n",a+b)
print("substraction is-\n",a-b)

addition is-
 [[ 5  6 11]
 [ 8  4  3]
 [ 4 17 16]]
substraction is-
 [[ 1  4 -5]
 [ 0  0  1]
 [-2 -1  2]]


In [ ]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C=np.random.randint(1,10,(3,2))
D=np.random.randint(1,10,(2,4))
np.matmul(C,D)

array([[ 41,  87, 117, 128],
       [ 28,  46,  74,  74],
       [ 15,  55,  53,  70]])

In [ ]:
#83.Create a matrix `E` and find its transpose.
E=np.random.randint(1,10,(3,3))
E.transpose()

array([[7, 4, 7],
       [1, 5, 9],
       [3, 6, 3]])

In [ ]:
#84.Generate a square matrix `F` and compute its determinant.
F=np.random.randint(1,10,(3,3))
np.linalg.det(F)

47.999999999999986

In [ ]:
#85.Create a square matrix `G` and find its inverse.
G=np.random.randint(1,10,(3,3))
np.linalg.inv(G)

array([[ 1.00000000e+00, -1.00000000e+00, -2.77555756e-17],
       [-1.00000000e+00,  1.17500000e+00, -2.25000000e-01],
       [-1.21430643e-18, -2.50000000e-02,  1.75000000e-01]])